[tool.setuptools]
packages = ["sandbox"]

[project]
name = "sandbox"
version = "0.1"

dependencies = [
  # Match versions preinstalled in Colab, as of 2024-07-11.
  "Jinja2==3.1.4",
  "numpy==1.25.2",
  "Pillow==9.4.0",
  "tensorflow==2.15.0",

  # Whatever works.
  "mujoco>=3.1.6",
]
